### ISSUE TITLE
can not connect to domain server via webRTC in container 

### ISSUE THREAD

**Issue by xiangxiaoc** [Misterblue/vircadia-domain-server-docker#2]
Hello, I run domain server with exposing 40102 port for webRTC connection:

```shell
docker run -d --name domainserver-docker \
  -p 40100:40100 -p 40102:40102 -p 40102:40102/udp \
  misterblue/domain-server
```

it doesn't work. Vircadia web cannot connect to the domain server, I wonder if I need to expose other ports. Then I tried using host network, it works. 

```shell
docker run -d --name domainserver-docker \
  --network host \
  misterblue/domain-server
```

Now I want to deploy many domain servers in my kubernetes cluster(only two work nodes...), some domain servers will be scheduled to the one node, so I can not use host network for each domian server. 

Either find the ports that need to expose or deploy the domain server in another special way. How do you solve the problem of webrtc connecting to the many domain servers in docker or in kubernetes?

**Comment by Misterblue** [comment]
The problem is that misterblue/domain-server is an old version of the domain-server and might not even have support for the web interface. I will delete the old images to eliminate future confusion.
HapticMonkey did a bunch of work on Vircadia Docker containers (https://forum.vircadia.com/t/deploy-a-vircadia-server-with-an-ubuntu-20-04-docker-container/268) and you might chat with him in the Discord group to see if he keeps a current image.
Also, it would be optimal of someone added the workflow rules on the Github repository to build a Docker image whenever the sources were updated.

**Comment by xiangxiaoc** [comment]
Thanks. I decide to deploy domain server by enabling host network to avoid webRTC random port problem. Then configure the web interface port (40100)/ websocket port (40102) and domain server port (40102/udp) using environment variables so that each domian server does not conflict with each other on one node.

share my kubernetes statefulset yaml:
```yaml
...
    spec:
      hostNetwork: true
      containers:
        - name: domain-server
          image: xxx.xxx.xxx/xxx/domainserver
          imagePullPolicy: Always
          env:
            - name: METAVERSE_URL
              value: https://xxx.xxx.xxx/metaverse-server
            - name: ICE_SERVER
              value: xxx.xxx.xxx:7337
            - name: HIFI_DOMAIN_SERVER_HTTP_PORT
              value: "$((port + 90))"
            - name: HIFI_DOMAIN_SERVER_HTTPS_PORT
              value: "$((port + 91))"
            - name: VIRCADIA_DOMAIN_SERVER_WS_PORT
              value: "$((port + 92))"
            - name: HIFI_DOMAIN_SERVER_PORT
              value: "$((port + 92))"
            - name: HIFI_DOMAIN_SERVER_DTLS_PORT
              value: "$((port + 93))"
            - name: VIRCADIA_DOMAIN_SERVER_EXPORTER_PORT
              value: "$((port + 94))"
            - name: VIRCADIA_DOMAIN_SERVER_METADATA_EXPORTER_PORT
              value: "$((port + 95))"
            - name: AC_MIN_LISTEN_UDP_PORT
              value: '${ac_min_listem_upd_port}'
            - name: AC_PROCESS_MAX
              value: '30'
          volumeMounts:
            - mountPath: /home/cadia/.local
              name: domainserver-data
            - mountPath: /home/cadia/logs
              name: domainserver-log
...
```
